### ISSUE TITLE
Information about development

### ISSUE THREAD

**Issue by lyahim** [studioilgranello/nuxt-jwt-auth#4]
Dear Developers,

I would like interest about this repository is actively maintained or left?
I think this is a nice tool and I would like to use it if actively maintained.

Thank you,
Mihaly

**Comment by davide-granello** [comment]
Hello @lyahim, we are currently using this library in various of our projects so yes we'll mantain it some way, until a more official nuxt module comes up that offers same functionality.

Since we have little extra time to work on it, we can not ensure to follow up on all issues and bugs that may be opened.
